name: Scheduled Job

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ALCHEMY_APIKEY: ${{ secrets.ALCHEMY_APIKEY }}
          ETHERSCAN_APIKEY: ${{ secrets.ETHERSCAN_APIKEY }}
      - run: |
          npm install
          node cli.js holders
          node cli.js fix-holders
          node cli.js sort-holders
